import React from 'react'
import Book from './Book'


const Dashboard = ({ department }) => {
  const articles = [
    {
      "title": "Introduction to Algorithms",
      "description": "Comprehensive guide to algorithms with detailed explanations.",
      "author": "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
      "genre": "Algorithms",
      "department": "Computer Science",
      "count": 9,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Lpringer Nature",
      "publisher_id": 234567
    },
    {
      "title": "Artificial Intelligence: A Modern Approach",
      "description": "Fundamental concepts and techniques in AI, covering a wide range of topics.",
      "author": "Stuart Russell, Peter Norvig",
      "genre": "Artificial Intelligence",
      "department": "Computer Science",
      "count": 12,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "KarperMollins Publishers",
      "publisher_id": 345678
    },
    {
      "title": "Clean Code: A Handbook of Agile Software Craftsmanship",
      "description": "Principles and best practices for writing clean, maintainable code.",
      "author": "Robert C. Martin",
      "genre": "Software Engineering",
      "department": "Computer Science",
      "count": 13,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Mengage Learning",
      "publisher_id": 901234
    },
    {
      "title": "Design Patterns: Elements of Reusable Object-Oriented Software",
      "description": "Classic book on design patterns for software development.",
      "author": "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
      "genre": "Software Engineering",
      "department": "Computer Science",
      "count": 8,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Lpringer Nature",
      "publisher_id": 234567
    },
    {
      "title": "The Pragmatic Programmer: Your Journey to Mastery",
      "description": "Practical advice for becoming a better programmer.",
      "author": "Andrew Hunt, David Thomas",
      "genre": "Software Engineering",
      "department": "Computer Science",
      "count": 10,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "JarperCollins Publishers",
      "publisher_id": 123456
    },
    {
      "title": "Code Complete: A Practical Handbook of Software Construction",
      "description": "Detailed guide to software construction best practices.",
      "author": "Steve McConnell",
      "genre": "Software Engineering",
      "department": "Computer Science",
      "count": 12,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Introduction to the Theory of Computation",
      "description": "Comprehensive text on computational theory and complexity.",
      "author": "Michael Sipser",
      "genre": "Computational Theory",
      "department": "Computer Science",
      "count": 13,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "The Art of Computer Programming",
      "description": "Seminal work covering many aspects of computer science.",
      "author": "Donald E. Knuth",
      "genre": "Algorithms",
      "department": "Computer Science",
      "count": 10,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "JarperCollins Publishers",
      "publisher_id": 123456
    },
    {
      "title": "Structure and Interpretation of Computer Programs",
      "description": "Foundational text on computer science principles and programming.",
      "author": "Harold Abelson, Gerald Jay Sussman",
      "genre": "Programming",
      "department": "Computer Science",
      "count": 10,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Bengage Learning",
      "publisher_id": 876543
    },
    {
      "title": "Computer Networks",
      "description": "Detailed introduction to the principles and practice of computer networking.",
      "author": "Andrew S. Tanenbaum, David J. Wetherall",
      "genre": "Networking",
      "department": "Computer Science",
      "count": 9,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "BcGraw-Hill Education",
      "publisher_id": 987654
    },
    {
      "title": "Database System Concepts",
      "description": "Comprehensive introduction to database systems.",
      "author": "Abraham Silberschatz, Henry F. Korth, S. Sudarshan",
      "genre": "Database Systems",
      "department": "Computer Science",
      "count": 12,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Operating System Concepts",
      "description": "In-depth look at the design and implementation of operating systems.",
      "author": "Abraham Silberschatz, Peter B. Galvin, Greg Gagne",
      "genre": "Operating Systems",
      "department": "Computer Science",
      "count": 9,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Nearson Education",
      "publisher_id": 654321
    },
    {
      "title": "Compilers: Principles, Techniques, and Tools",
      "description": "Authoritative guide on compiler construction.",
      "author": "Alfred V. Aho, Monica S. Lam, Ravi Sethi, Jeffrey D. Ullman",
      "genre": "Compilers",
      "department": "Computer Science",
      "count": 13,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Mengage Learning",
      "publisher_id": 901234
    },
    {
      "title": "Deep Learning",
      "description": "Comprehensive introduction to deep learning theory and practice.",
      "author": "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
      "genre": "Machine Learning",
      "department": "Computer Science",
      "count": 13,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Computer Architecture: A Quantitative Approach",
      "description": "In-depth exploration of computer architecture with a quantitative approach.",
      "author": "John L. Hennessy, David A. Patterson",
      "genre": "Computer Architecture",
      "department": "Computer Science",
      "count": 15,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "The C Programming Language",
      "description": "Classic book on C programming by the language's creators.",
      "author": "Brian W. Kernighan, Dennis M. Ritchie",
      "genre": "Programming",
      "department": "Computer Science",
      "count": 8,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Python Crash Course",
      "description": "Hands-on guide to programming with Python for beginners.",
      "author": "Eric Matthes",
      "genre": "Programming",
      "department": "Computer Science",
      "count": 12,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Lpringer Nature",
      "publisher_id": 234567
    },
    {
      "title": "Introduction to Machine Learning with Python",
      "description": "Practical guide to applying machine learning with Python.",
      "author": "Andreas C. Müller, Sarah Guido",
      "genre": "Machine Learning",
      "department": "Computer Science",
      "count": 14,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Bengage Learning",
      "publisher_id": 876543
    },
    {
      "title": "Patterns of Enterprise Application Architecture",
      "description": "Guide to building enterprise applications with design patterns.",
      "author": "Martin Fowler",
      "genre": "Software Engineering",
      "department": "Computer Science",
      "count": 15,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Algorithms Unlocked",
      "description": "Accessible introduction to fundamental algorithms.",
      "author": "Thomas H. Cormen",
      "genre": "Algorithms",
      "department": "Computer Science",
      "count": 8,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Engineering Mechanics: Dynamics",
      "description": "Comprehensive guide to the principles of dynamics in engineering mechanics.",
      "author": "J. L. Meriam, L. G. Kraige",
      "genre": "Dynamics",
      "department": "Mechanical Engineering",
      "count": 11,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Fundamentals of Thermodynamics",
      "description": "Detailed introduction to thermodynamic principles and applications.",
      "author": "Richard E. Sonntag, Claus Borgnakke, Gordon J. Van Wylen",
      "genre": "Thermodynamics",
      "department": "Mechanical Engineering",
      "count": 15,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Mechanical Engineering Design",
      "description": "In-depth look at design principles and practices in mechanical engineering.",
      "author": "J. E. Shigley, Charles R. Mischke, Richard G. Budynas",
      "genre": "Design",
      "department": "Mechanical Engineering",
      "count": 9,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Materials Science and Engineering: An Introduction",
      "description": "Comprehensive text on the fundamentals of materials science and engineering.",
      "author": "William D. Callister Jr.",
      "genre": "Materials Science",
      "department": "Mechanical Engineering",
      "count": 10,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Lpringer Nature",
      "publisher_id": 234567
    },
    {
      "title": "Fluid Mechanics",
      "description": "Thorough exploration of fluid mechanics principles and applications.",
      "author": "Frank M. White",
      "genre": "Fluid Mechanics",
      "department": "Mechanical Engineering",
      "count": 10,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Bengage Learning",
      "publisher_id": 876543
    },
    {
      "title": "Mechanical Vibrations",
      "description": "Detailed guide to the study of mechanical vibrations.",
      "author": "S. S. Rao",
      "genre": "Vibrations",
      "department": "Mechanical Engineering",
      "count": 9,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Introduction to Finite Elements in Engineering",
      "description": "Comprehensive introduction to finite element analysis and its applications.",
      "author": "Tirupathi R. Chandrupatla, Ashok D. Belegundu",
      "genre": "Finite Element Analysis",
      "department": "Mechanical Engineering",
      "count": 14,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "JarperCollins Publishers",
      "publisher_id": 123456
    },
    {
      "title": "Heat and Mass Transfer: Fundamentals and Applications",
      "description": "Fundamental concepts and applications of heat and mass transfer.",
      "author": "Yunus A. Cengel, Afshin J. Ghajar",
      "genre": "Heat Transfer",
      "department": "Mechanical Engineering",
      "count": 12,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Engineering Mechanics: Statics",
      "description": "Comprehensive guide to the principles of statics in engineering mechanics.",
      "author": "J. L. Meriam, L. G. Kraige",
      "genre": "Statics",
      "department": "Mechanical Engineering",
      "count": 15,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Mengage Learning",
      "publisher_id": 901234
    },
    {
      "title": "Theory of Machines and Mechanisms",
      "description": "Detailed study of the kinematics and dynamics of machines and mechanisms.",
      "author": "John J. Uicker Jr., Gordon R. Pennock, Joseph E. Shigley",
      "genre": "Mechanisms",
      "department": "Mechanical Engineering",
      "count": 15,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Fundamentals of Machine Component Design",
      "description": "Comprehensive text on the design of machine components.",
      "author": "Robert C. Juvinall, Kurt M. Marshek",
      "genre": "Design",
      "department": "Mechanical Engineering",
      "count": 14,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Nearson Education",
      "publisher_id": 654321
    },
    {
      "title": "Advanced Engineering Mathematics",
      "description": "Essential mathematical concepts and techniques for engineering.",
      "author": "Erwin Kreyszig",
      "genre": "Mathematics",
      "department": "Mechanical Engineering",
      "count": 12,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "KarperMollins Publishers",
      "publisher_id": 345678
    },
    {
      "title": "Mechanical Behavior of Materials",
      "description": "In-depth exploration of the behavior of materials under different conditions.",
      "author": "Norman E. Dowling",
      "genre": "Materials Science",
      "department": "Mechanical Engineering",
      "count": 15,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Lpringer Nature",
      "publisher_id": 234567
    },
    {
      "title": "Introduction to Robotics: Mechanics and Control",
      "description": "Comprehensive introduction to the mechanics and control of robots.",
      "author": "John J. Craig",
      "genre": "Robotics",
      "department": "Mechanical Engineering",
      "count": 8,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Principles of Heat Transfer",
      "description": "Thorough exploration of heat transfer principles and applications.",
      "author": "Frank Kreith, Raj M. Manglik, Mark S. Bohn",
      "genre": "Heat Transfer",
      "department": "Mechanical Engineering",
      "count": 12,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Fundamentals of Fluid Mechanics",
      "description": "Comprehensive guide to fluid mechanics principles and practices.",
      "author": "Bruce R. Munson, Donald F. Young, Theodore H. Okiishi, Wade W. Huebsch",
      "genre": "Fluid Mechanics",
      "department": "Mechanical Engineering",
      "count": 15,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Engineering Vibrations",
      "description": "Detailed study of vibration analysis and its engineering applications.",
      "author": "Daniel J. Inman",
      "genre": "Vibrations",
      "department": "Mechanical Engineering",
      "count": 11,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Mengage Learning",
      "publisher_id": 901234
    },
    {
      "title": "Mechanics of Materials",
      "description": "Comprehensive text on the mechanics and behavior of materials.",
      "author": "Ferdinand P. Beer, E. Russell Johnston Jr., John T. DeWolf, David F. Mazurek",
      "genre": "Materials Science",
      "department": "Mechanical Engineering",
      "count": 8,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "BcGraw-Hill Education",
      "publisher_id": 987654
    },
    {
      "title": "Introduction to Engineering Experimentation",
      "description": "Guide to the principles and practices of engineering experimentation.",
      "author": "Anthony J. Wheeler, Ahmad R. Ganji",
      "genre": "Experimentation",
      "department": "Mechanical Engineering",
      "count": 15,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Lpringer Nature",
      "publisher_id": 234567
    },
    {
      "title": "Mechanics of Composite Materials",
      "description": "Comprehensive text on the mechanical behavior of composite materials.",
      "author": "Robert M. Jones",
      "genre": "Materials Science",
      "department": "Mechanical Engineering",
      "count": 14,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Nearson Education",
      "publisher_id": 654321
    },
    {
      "title": "Electrical Engineering: Principles and Applications",
      "description": "Comprehensive guide to fundamental principles and applications of electrical engineering.",
      "author": "Allan R. Hambley",
      "genre": "General Electrical Engineering",
      "department": "Electrical Engineering",
      "count": 15,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Nearson Education",
      "publisher_id": 654321
    },
    {
      "title": "Fundamentals of Electric Circuits",
      "description": "In-depth study of electric circuit theory and practice.",
      "author": "Charles K. Alexander, Matthew N. O. Sadiku",
      "genre": "Circuits",
      "department": "Electrical Engineering",
      "count": 8,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "KarperMollins Publishers",
      "publisher_id": 345678
    },
    {
      "title": "Power System Analysis and Design",
      "description": "Detailed introduction to power systems and their design.",
      "author": "J. Duncan Glover, Mulukutla S. Sarma, Thomas Overbye",
      "genre": "Power Systems",
      "department": "Electrical Engineering",
      "count": 13,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Microelectronic Circuits",
      "description": "Comprehensive guide to the principles and applications of microelectronic circuits.",
      "author": "Adel S. Sedra, Kenneth C. Smith",
      "genre": "Microelectronics",
      "department": "Electrical Engineering",
      "count": 12,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Mengage Learning",
      "publisher_id": 901234
    },
    {
      "title": "Digital Design: With an Introduction to the Verilog HDL",
      "description": "Fundamentals of digital design and introduction to Verilog HDL.",
      "author": "M. Morris Mano, Michael D. Ciletti",
      "genre": "Digital Design",
      "department": "Electrical Engineering",
      "count": 12,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Signals and Systems",
      "description": "Introduction to the theory and application of signals and systems.",
      "author": "Alan V. Oppenheim, Alan S. Willsky, S. Hamid Nawab",
      "genre": "Signals and Systems",
      "department": "Electrical Engineering",
      "count": 15,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Bengage Learning",
      "publisher_id": 876543
    },
    {
      "title": "Control Systems Engineering",
      "description": "Comprehensive guide to control systems and their applications.",
      "author": "Norman S. Nise",
      "genre": "Control Systems",
      "department": "Electrical Engineering",
      "count": 15,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Electric Machinery Fundamentals",
      "description": "Detailed study of electric machinery and its operation.",
      "author": "Stephen J. Chapman",
      "genre": "Electric Machinery",
      "department": "Electrical Engineering",
      "count": 9,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "JarperCollins Publishers",
      "publisher_id": 123456
    },
    {
      "title": "Electromagnetic Fields and Waves",
      "description": "Introduction to electromagnetic theory and applications.",
      "author": "Paul Lorrain, Dale Corson, François Lorrain",
      "genre": "Electromagnetics",
      "department": "Electrical Engineering",
      "count": 11,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Nearson Education",
      "publisher_id": 654321
    },
    {
      "title": "Communication Systems",
      "description": "Comprehensive guide to the principles of communication systems.",
      "author": "Simon Haykin",
      "genre": "Communication Systems",
      "department": "Electrical Engineering",
      "count": 12,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Mengage Learning",
      "publisher_id": 901234
    },
    {
      "title": "Power Electronics: Converters, Applications, and Design",
      "description": "Detailed introduction to power electronics and their applications.",
      "author": "Ned Mohan, Tore M. Undeland, William P. Robbins",
      "genre": "Power Electronics",
      "department": "Electrical Engineering",
      "count": 10,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Digital Signal Processing: Principles, Algorithms, and Applications",
      "description": "Comprehensive guide to the principles and applications of digital signal processing.",
      "author": "John G. Proakis, Dimitris G. Manolakis",
      "genre": "Digital Signal Processing",
      "department": "Electrical Engineering",
      "count": 14,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "KarperMollins Publishers",
      "publisher_id": 345678
    },
    {
      "title": "Electric Power Systems: A First Course",
      "description": "Introductory guide to electric power systems and their operation.",
      "author": "Ned Mohan",
      "genre": "Power Systems",
      "department": "Electrical Engineering",
      "count": 15,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Analog Integrated Circuit Design",
      "description": "Comprehensive guide to the design of analog integrated circuits.",
      "author": "David A. Johns, Ken Martin",
      "genre": "Analog Design",
      "department": "Electrical Engineering",
      "count": 12,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Electromagnetics for Engineers",
      "description": "Introduction to the principles and applications of electromagnetics for engineers.",
      "author": "Fawwaz T. Ulaby",
      "genre": "Electromagnetics",
      "department": "Electrical Engineering",
      "count": 12,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Modern Control Engineering",
      "description": "Comprehensive guide to modern control engineering principles and practices.",
      "author": "Katsuhiko Ogata",
      "genre": "Control Systems",
      "department": "Electrical Engineering",
      "count": 12,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Fundamentals of Applied Electromagnetics",
      "description": "Introductory guide to applied electromagnetics and its applications.",
      "author": "Fawwaz T. Ulaby, Umberto Ravaioli",
      "genre": "Electromagnetics",
      "department": "Electrical Engineering",
      "count": 13,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Mengage Learning",
      "publisher_id": 901234
    },
    {
      "title": "Introduction to Electric Circuits",
      "description": "Detailed introduction to electric circuit analysis and design.",
      "author": "Richard C. Dorf, James A. Svoboda",
      "genre": "Circuits",
      "department": "Electrical Engineering",
      "count": 8,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Principles of Power Systems",
      "description": "Comprehensive guide to the principles of power systems engineering.",
      "author": "V. K. Mehta, Rohit Mehta",
      "genre": "Power Systems",
      "department": "Electrical Engineering",
      "count": 15,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Nearson Education",
      "publisher_id": 654321
    },
    {
      "title": "Introduction to Wireless and Mobile Systems",
      "description": "Introductory guide to the principles of wireless and mobile communication systems.",
      "author": "Dharma P. Agrawal, Qing-An Zeng",
      "genre": "Wireless Communication",
      "department": "Electrical Engineering",
      "count": 11,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Lpringer Nature",
      "publisher_id": 234567
    },
    {
      "title": "Principles of Foundation Engineering",
      "description": "Comprehensive guide to the principles and practices of foundation engineering.",
      "author": "Braja M. Das",
      "genre": "Foundation Engineering",
      "department": "Civil Engineering",
      "count": 14,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Structural Analysis",
      "description": "In-depth study of structural analysis methods and applications.",
      "author": "R. C. Hibbeler",
      "genre": "Structural Engineering",
      "department": "Civil Engineering",
      "count": 9,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Concrete Technology",
      "description": "Detailed introduction to concrete properties, production, and testing.",
      "author": "A. M. Neville, J. J. Brooks",
      "genre": "Materials Engineering",
      "department": "Civil Engineering",
      "count": 10,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Water Resources Engineering",
      "description": "Comprehensive text on water resources engineering and management.",
      "author": "Larry W. Mays",
      "genre": "Water Resources",
      "department": "Civil Engineering",
      "count": 14,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Transportation Engineering and Planning",
      "description": "Fundamentals of transportation engineering and planning concepts.",
      "author": "C. S. Papacostas, P. D. Prevedouros",
      "genre": "Transportation Engineering",
      "department": "Civil Engineering",
      "count": 12,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Engineering Geology: An Environmental Approach",
      "description": "Introduction to the principles and applications of engineering geology.",
      "author": "Perry H. Rahn",
      "genre": "Geotechnical Engineering",
      "department": "Civil Engineering",
      "count": 10,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Design of Reinforced Concrete",
      "description": "Comprehensive guide to the design principles of reinforced concrete structures.",
      "author": "Jack C. McCormac, Russell H. Brown",
      "genre": "Structural Engineering",
      "department": "Civil Engineering",
      "count": 10,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "KarperMollins Publishers",
      "publisher_id": 345678
    },
    {
      "title": "Principles of Geotechnical Engineering",
      "description": "Detailed introduction to the principles of geotechnical engineering.",
      "author": "Braja M. Das",
      "genre": "Geotechnical Engineering",
      "department": "Civil Engineering",
      "count": 8,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Soil Mechanics in Engineering Practice",
      "description": "Comprehensive text on the principles and applications of soil mechanics.",
      "author": "Karl Terzaghi, Ralph B. Peck, Gholamreza Mesri",
      "genre": "Geotechnical Engineering",
      "department": "Civil Engineering",
      "count": 9,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Construction Planning, Equipment, and Methods",
      "description": "Guide to the planning and methods of construction projects.",
      "author": "Robert L. Peurifoy, Clifford J. Schexnayder, Aviad Shapira, Robert Schmitt",
      "genre": "Construction Management",
      "department": "Civil Engineering",
      "count": 15,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Nearson Education",
      "publisher_id": 654321
    },
    {
      "title": "Environmental Engineering: Fundamentals, Sustainability, Design",
      "description": "Comprehensive guide to environmental engineering principles and sustainable design.",
      "author": "James R. Mihelcic, Julie B. Zimmerman",
      "genre": "Environmental Engineering",
      "department": "Civil Engineering",
      "count": 13,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Lpringer Nature",
      "publisher_id": 234567
    },
    {
      "title": "Steel Design",
      "description": "Introduction to the principles and practices of structural steel design.",
      "author": "William T. Segui",
      "genre": "Structural Engineering",
      "department": "Civil Engineering",
      "count": 9,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Hydrology and Hydraulic Systems",
      "description": "Detailed study of hydrology and hydraulic engineering systems.",
      "author": "Ram S. Gupta",
      "genre": "Hydraulic Engineering",
      "department": "Civil Engineering",
      "count": 10,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Bengage Learning",
      "publisher_id": 876543
    },
    {
      "title": "Construction Project Management: A Practical Guide to Field Construction Management",
      "description": "Practical guide to the management of construction projects.",
      "author": "S. Keoki Sears, Glenn A. Sears, Richard H. Clough, Jerald L. Rounds, Robert O. Segner",
      "genre": "Construction Management",
      "department": "Civil Engineering",
      "count": 9,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Structural Steel Design",
      "description": "Comprehensive text on the design of structural steel elements and systems.",
      "author": "Jack C. McCormac, Stephen F. Csernak",
      "genre": "Structural Engineering",
      "department": "Civil Engineering",
      "count": 13,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Geotechnical Engineering: Principles and Practices",
      "description": "In-depth guide to the principles and practices of geotechnical engineering.",
      "author": "Donald P. Coduto, Man-chu Ronald Yeung, William A. Kitch",
      "genre": "Geotechnical Engineering",
      "department": "Civil Engineering",
      "count": 12,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Masonry Structures: Behavior and Design",
      "description": "Comprehensive guide to the behavior and design of masonry structures.",
      "author": "Robert G. Drysdale, Ahmad A. Hamid, Lawrie R. Baker",
      "genre": "Structural Engineering",
      "department": "Civil Engineering",
      "count": 10,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "Lpringer Nature",
      "publisher_id": 234567
    },
    {
      "title": "Advanced Mechanics of Materials and Applied Elasticity",
      "description": "Detailed study of advanced mechanics of materials and applied elasticity.",
      "author": "Ansel C. Ugural, Saul K. Fenster",
      "genre": "Materials Engineering",
      "department": "Civil Engineering",
      "count": 13,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Introduction to Transportation Engineering",
      "description": "Comprehensive guide to the fundamentals of transportation engineering.",
      "author": "William W. Hay",
      "genre": "Transportation Engineering",
      "department": "Civil Engineering",
      "count": 9,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Mengage Learning",
      "publisher_id": 901234
    },
    {
      "title": "Bridge Engineering: Substructure Design",
      "description": "In-depth guide to the design principles of bridge substructures.",
      "author": "W.F. Chen, Lian Duan",
      "genre": "Structural Engineering",
      "department": "Civil Engineering",
      "count": 9,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Chemical Engineering: Principles and Practice",
      "description": "Comprehensive guide to chemical engineering principles and industrial practice.",
      "author": "George DeLancey",
      "genre": "General Chemical Engineering",
      "department": "Chemical Engineering",
      "count": 8,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Transport Processes and Separation Process Principles",
      "description": "Detailed introduction to transport processes and separation techniques.",
      "author": "Christie John Geankoplis",
      "genre": "Transport Processes",
      "department": "Chemical Engineering",
      "count": 15,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Chemical Engineering Design: Principles, Practice and Economics of Plant and Process Design",
      "description": "Guide to the principles and practices of chemical engineering design.",
      "author": "Gavin Towler, Ray Sinnott",
      "genre": "Design",
      "department": "Chemical Engineering",
      "count": 10,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Elements of Chemical Reaction Engineering",
      "description": "Fundamentals of chemical reaction engineering and reactor design.",
      "author": "H. Scott Fogler",
      "genre": "Reaction Engineering",
      "department": "Chemical Engineering",
      "count": 10,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Introduction to Chemical Engineering Thermodynamics",
      "description": "Comprehensive text on the principles of chemical engineering thermodynamics.",
      "author": "J. M. Smith, Hendrick Van Ness, Michael Abbott",
      "genre": "Thermodynamics",
      "department": "Chemical Engineering",
      "count": 11,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Mengage Learning",
      "publisher_id": 901234
    },
    {
      "title": "Process Dynamics and Control",
      "description": "In-depth study of process dynamics and control strategies.",
      "author": "Dale E. Seborg, Thomas F. Edgar, Duncan A. Mellichamp, Francis J. Doyle III",
      "genre": "Process Control",
      "department": "Chemical Engineering",
      "count": 14,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Chemical Process Safety: Fundamentals with Applications",
      "description": "Comprehensive guide to the fundamentals of chemical process safety.",
      "author": "Daniel A. Crowl, Joseph F. Louvar",
      "genre": "Safety",
      "department": "Chemical Engineering",
      "count": 9,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "KarperMollins Publishers",
      "publisher_id": 345678
    },
    {
      "title": "Perry's Chemical Engineers' Handbook",
      "description": "Essential reference for chemical engineering practice and principles.",
      "author": "Don W. Green, Marylee W. Southard",
      "genre": "Reference",
      "department": "Chemical Engineering",
      "count": 10,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Biochemical Engineering Fundamentals",
      "description": "Detailed introduction to the principles and applications of biochemical engineering.",
      "author": "James E. Bailey, David F. Ollis",
      "genre": "Biochemical Engineering",
      "department": "Chemical Engineering",
      "count": 10,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Principles of Bioseparations Engineering",
      "description": "Comprehensive guide to the principles and practices of bioseparations.",
      "author": "Roger G. Harrison, Paul W. Todd, Scott R. Rudge, Demetri P. Petrides",
      "genre": "Bioseparations",
      "department": "Chemical Engineering",
      "count": 9,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "KarperMollins Publishers",
      "publisher_id": 345678
    },
    {
      "title": "Fundamentals of Momentum, Heat, and Mass Transfer",
      "description": "Essential concepts and principles of momentum, heat, and mass transfer.",
      "author": "James R. Welty, Gregory L. Rorrer, David G. Foster",
      "genre": "Transport Processes",
      "department": "Chemical Engineering",
      "count": 11,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Separation Process Principles",
      "description": "Detailed study of the principles and techniques of separation processes.",
      "author": "J. D. Seader, Ernest J. Henley, D. Keith Roper",
      "genre": "Separation Processes",
      "department": "Chemical Engineering",
      "count": 12,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Principles and Modern Applications of Mass Transfer Operations",
      "description": "Comprehensive guide to the principles and applications of mass transfer.",
      "author": "Jaime Benitez",
      "genre": "Mass Transfer",
      "department": "Chemical Engineering",
      "count": 11,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Chemical Engineering Kinetics",
      "description": "Fundamentals of chemical reaction kinetics and reactor design.",
      "author": "J. M. Smith",
      "genre": "Reaction Engineering",
      "department": "Chemical Engineering",
      "count": 11,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Bengage Learning",
      "publisher_id": 876543
    },
    {
      "title": "Process Design: Principles and Practices",
      "description": "Guide to the principles and practices of chemical process design.",
      "author": "Warren D. Seider, J. D. Seader, Daniel R. Lewin, Soemantri Widagdo",
      "genre": "Design",
      "department": "Chemical Engineering",
      "count": 13,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "KarperMollins Publishers",
      "publisher_id": 345678
    },
    {
      "title": "Fluid Mechanics for Chemical Engineers",
      "description": "Detailed introduction to fluid mechanics principles and applications in chemical engineering.",
      "author": "James O. Wilkes",
      "genre": "Fluid Mechanics",
      "department": "Chemical Engineering",
      "count": 9,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "KarperMollins Publishers",
      "publisher_id": 345678
    },
    {
      "title": "Introduction to Catalysis and Industrial Catalytic Processes",
      "description": "Comprehensive text on the principles and applications of catalysis.",
      "author": "Robert J. Farrauto, Lucas Dorazio, Calvin H. Bartholomew",
      "genre": "Catalysis",
      "department": "Chemical Engineering",
      "count": 9,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "JarperCollins Publishers",
      "publisher_id": 123456
    },
    {
      "title": "Chemical Engineering Fluid Mechanics",
      "description": "Guide to the principles and applications of fluid mechanics in chemical engineering.",
      "author": "Ron Darby, Raj P. Chhabra",
      "genre": "Fluid Mechanics",
      "department": "Chemical Engineering",
      "count": 10,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Mengage Learning",
      "publisher_id": 901234
    },
    {
      "title": "Essentials of Chemical Reaction Engineering",
      "description": "Fundamental principles and applications of chemical reaction engineering.",
      "author": "H. Scott Fogler",
      "genre": "Reaction Engineering",
      "department": "Chemical Engineering",
      "count": 11,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Principles of Chemical Engineering Processes: Material and Energy Balances",
      "description": "Comprehensive guide to material and energy balance calculations in chemical processes.",
      "author": "Nayef Ghasem, Redhouane Henda",
      "genre": "Process Engineering",
      "department": "Chemical Engineering",
      "count": 9,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Nearson Education",
      "publisher_id": 654321
    },
    {
      "title": "Introduction to Quantum Mechanics",
      "description": "Fundamental principles and applications of quantum mechanics.",
      "author": "David J. Griffiths, Darrell F. Schroeter",
      "genre": "Quantum Mechanics",
      "department": "Engineering Physics",
      "count": 9,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "KarperMollins Publishers",
      "publisher_id": 345678
    },
    {
      "title": "Classical Mechanics",
      "description": "Comprehensive guide to classical mechanics principles and applications.",
      "author": "Herbert Goldstein, Charles Poole, John Safko",
      "genre": "Classical Mechanics",
      "department": "Engineering Physics",
      "count": 9,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Modern Physics for Scientists and Engineers",
      "description": "Introduction to the concepts and principles of modern physics.",
      "author": "Stephen T. Thornton, Andrew Rex",
      "genre": "Modern Physics",
      "department": "Engineering Physics",
      "count": 11,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Mengage Learning",
      "publisher_id": 901234
    },
    {
      "title": "Engineering Electromagnetics",
      "description": "Detailed study of electromagnetics and its engineering applications.",
      "author": "William H. Hayt, John A. Buck",
      "genre": "Electromagnetics",
      "department": "Engineering Physics",
      "count": 9,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Thermodynamics: An Engineering Approach",
      "description": "Fundamentals of thermodynamics with practical engineering applications.",
      "author": "Yunus A. Çengel, Michael A. Boles",
      "genre": "Thermodynamics",
      "department": "Engineering Physics",
      "count": 14,
      "vendor": "Indian Book Depot",
      "vendor_id": 1003,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Optics",
      "description": "Comprehensive guide to the principles and applications of optics.",
      "author": "Eugene Hecht",
      "genre": "Optics",
      "department": "Engineering Physics",
      "count": 10,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Solid State Physics",
      "description": "Fundamental concepts and applications of solid state physics.",
      "author": "Neil W. Ashcroft, N. David Mermin",
      "genre": "Solid State Physics",
      "department": "Engineering Physics",
      "count": 10,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Statistical Physics",
      "description": "Comprehensive introduction to statistical mechanics and its applications.",
      "author": "R. K. Pathria, Paul D. Beale",
      "genre": "Statistical Physics",
      "department": "Engineering Physics",
      "count": 14,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Fundamentals of Photonics",
      "description": "In-depth study of photonics principles and applications.",
      "author": "Bahaa E. A. Saleh, Malvin Carl Teich",
      "genre": "Photonics",
      "department": "Engineering Physics",
      "count": 8,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "Nuclear Physics: Principles and Applications",
      "description": "Introduction to nuclear physics principles and their practical applications.",
      "author": "John Lilley",
      "genre": "Nuclear Physics",
      "department": "Engineering Physics",
      "count": 10,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Dambridge University Press",
      "publisher_id": 890123
    },
    {
      "title": "The Physics of Solids",
      "description": "Comprehensive guide to the physics and properties of solid materials.",
      "author": "Richard Turton",
      "genre": "Solid State Physics",
      "department": "Engineering Physics",
      "count": 9,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "JarperCollins Publishers",
      "publisher_id": 123456
    },
    {
      "title": "Introduction to Plasma Physics and Controlled Fusion",
      "description": "Fundamentals of plasma physics and controlled nuclear fusion.",
      "author": "Francis F. Chen",
      "genre": "Plasma Physics",
      "department": "Engineering Physics",
      "count": 11,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "An Introduction to Thermal Physics",
      "description": "Fundamental principles and applications of thermal physics.",
      "author": "Daniel V. Schroeder",
      "genre": "Thermal Physics",
      "department": "Engineering Physics",
      "count": 11,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "Introduction to Solid State Physics",
      "description": "Comprehensive introduction to the principles of solid state physics.",
      "author": "Charles Kittel",
      "genre": "Solid State Physics",
      "department": "Engineering Physics",
      "count": 9,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "Loxpord University Press",
      "publisher_id": 789012
    },
    {
      "title": "Applied Physics for Engineers",
      "description": "Practical applications of physics principles for engineering.",
      "author": "Neeraj Mehta",
      "genre": "Applied Physics",
      "department": "Engineering Physics",
      "count": 8,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Lpringer Nature",
      "publisher_id": 234567
    },
    {
      "title": "Electronics and Communications for Scientists and Engineers",
      "description": "Detailed introduction to electronics and communication systems.",
      "author": "Martin Plonus",
      "genre": "Electronics",
      "department": "Engineering Physics",
      "count": 14,
      "vendor": "World Book Store",
      "vendor_id": 1007,
      "publisher": "Bengage Learning",
      "publisher_id": 876543
    },
    {
      "title": "Classical Electrodynamics",
      "description": "In-depth study of the principles and applications of classical electrodynamics.",
      "author": "John David Jackson",
      "genre": "Electrodynamics",
      "department": "Engineering Physics",
      "count": 14,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "KarperMollins Publishers",
      "publisher_id": 345678
    },
    {
      "title": "Quantum Physics: A Fundamental Approach to Modern Physics",
      "description": "Fundamental principles of quantum physics with modern applications.",
      "author": "John S. Townsend",
      "genre": "Quantum Physics",
      "department": "Engineering Physics",
      "count": 10,
      "vendor": "Kitab Mahal",
      "vendor_id": 1004,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    },
    {
      "title": "The Feynman Lectures on Physics",
      "description": "Comprehensive collection of lectures covering fundamental physics concepts.",
      "author": "Richard P. Feynman, Robert B. Leighton, Matthew Sands",
      "genre": "General Physics",
      "department": "Engineering Physics",
      "count": 8,
      "vendor": "Sterling Book House",
      "vendor_id": 1005,
      "publisher": "Rohn Wiley & Sons",
      "publisher_id": 456789
    },
    {
      "title": "Computational Physics",
      "description": "Introduction to computational methods for solving physics problems.",
      "author": "Nicholas J. Giordano, Hisao Nakanishi",
      "genre": "Computational Physics",
      "department": "Engineering Physics",
      "count": 14,
      "vendor": "Amazon India",
      "vendor_id": 1006,
      "publisher": "Dearson Education",
      "publisher_id": 567890
    }
  ]
  // const filteredbooks = articles
  //   .filter(article =>
  //     (department ? article.department === department : true) &&
  //     (searchQuery ? article.title.toLowerCase().includes(searchQuery.toLowerCase()) || article.description.toLowerCase().includes(searchQuery.toLowerCase()) : true)
  //   );
  const filteredbooks = articles.filter(article => article.department === department)
  return (
    <div>
      <div className="container " style={{marginTop:'60px'}}>
        <div className="row">
          {filteredbooks.map((article, index) => (
            <div className="col-12 col-sm-6 col-md-4 col-lg-3 mb-4" key={index}>
              <Book
                // title={article.title.slice(0, 50)} 
                // description={article.description.slice(0, 80)} 
                // count={article.count} 
                title={article.title ? article.title.slice(0, 50) : 'No Title'}
                description={article.description ? article.author.slice(0,50) : 'No Description'}
                count={article.count || 0}
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
